#!/usr/bin/env python3
"""Build skills-index.json from every SKILL.md in the repository."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "skills-index.json"
SKILL_FILENAME = "SKILL.md"
SKIP_DIR_NAMES = {".git", "node_modules", "__pycache__"}


def parse_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path} is missing YAML frontmatter")

    parts = text.split("---", 2)
    if len(parts) < 3:
        raise ValueError(f"{path} has incomplete YAML frontmatter")

    data = yaml.safe_load(parts[1]) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} frontmatter is not a mapping")
    return data


def normalize_description(value: Any) -> str:
    if value is None:
        return ""
    return " ".join(str(value).split())


def normalize_sources(value: Any, path: Path) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value] if value else []
    if isinstance(value, list):
        return [str(item) for item in value if item is not None and str(item) != ""]
    raise ValueError(f"{path} sources must be a list or string")


def skill_entry(path: Path, repo_root: Path) -> dict[str, Any]:
    data = parse_frontmatter(path)
    metadata = data.get("metadata") or {}
    if not isinstance(metadata, dict):
        metadata = {}

    name = data.get("name")
    if not name:
        raise ValueError(f"{path} is missing name")

    relative_path = path.parent.relative_to(repo_root).as_posix()
    category = metadata.get("category") or data.get("category")

    return {
        "name": str(name),
        "path": relative_path,
        "category": category,
        "sources": normalize_sources(
            metadata.get("sources", data.get("sources")), path
        ),
        "description": normalize_description(data.get("description")),
    }


def collect_skills(repo_root: Path) -> list[dict[str, Any]]:
    skills: list[dict[str, Any]] = []
    for path in sorted(repo_root.rglob(SKILL_FILENAME)):
        if any(part in SKIP_DIR_NAMES for part in path.parts):
            continue
        skills.append(skill_entry(path, repo_root))
    skills.sort(key=lambda skill: skill["path"])
    return skills


def compute_flattened_slug(path: str) -> str | None:
    parts = path.strip("/").split("/")
    if len(parts) <= 1:
        return None
    return "-".join(parts[-2:])


def find_duplicate_leaf_slugs(skills: list[dict[str, Any]]) -> dict[str, list[str]]:
    by_leaf: dict[str, list[str]] = {}
    for skill in skills:
        leaf = skill["path"].split("/")[-1]
        by_leaf.setdefault(leaf, []).append(skill["path"])
    return {leaf: paths for leaf, paths in by_leaf.items() if len(paths) > 1}


INDEX_README = (
    "AUTO-GENERATED. Do not edit this file. Update SKILL.md frontmatter instead, "
    "then run python .github/scripts/generate_skill_index.py "
    "(also regenerated on merge to main)."
)


def render_index(skills: list[dict[str, Any]]) -> str:
    return (
        json.dumps(
            {
                "$comment": INDEX_README,
                "skills": skills,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )


def write_index(skills: list[dict[str, Any]], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_index(skills), encoding="utf-8")


def check(skills: list[dict[str, Any]], output: Path) -> int:
    duplicates = find_duplicate_leaf_slugs(skills)
    if duplicates:
        for leaf, paths in duplicates.items():
            print(f"Duplicate skill slug {leaf!r}:", file=sys.stderr)
            for path in paths:
                suggestion = compute_flattened_slug(path)
                if suggestion:
                    print(
                        f"  {path}  ->  suggested folder name: {suggestion!r}",
                        file=sys.stderr,
                    )
                else:
                    print(
                        f"  {path}  (pick a unique folder name)",
                        file=sys.stderr,
                    )
        print(
            "\nThe slug comes from the skill's directory name, not its `name` "
            "frontmatter field. If you just added one of these, rename its "
            "directory to the suggested folder name above, e.g.:\n"
            "  git mv sales/analytics sales/sales-analytics",
            file=sys.stderr,
        )
        return 1

    expected = render_index(skills)
    actual = output.read_text(encoding="utf-8") if output.exists() else None
    if actual != expected:
        print(
            f"{output} is stale — run python .github/scripts/generate_skill_index.py",
            file=sys.stderr,
        )
        return 1

    print(f"OK: {len(skills)} skills, no duplicate slugs, index up to date")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate without writing; exit 1 on duplicate leaf slugs or a stale index file",
    )
    args = parser.parse_args(argv)

    root = args.root.resolve()
    output = args.output.resolve()
    skills = collect_skills(root)

    if args.check:
        return check(skills, output)

    write_index(skills, output)
    print(f"Wrote {len(skills)} skills to {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
